services:
  # Oracle Database
  database:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=Oracle123
      - APP_USER=appuser
      - APP_USER_PASSWORD=Oracle123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database:/container-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Spring Boot Backend
  backend:
    image: ghcr.io/luetzen/docker-and-kubernetes/backend:latest
    container_name: backend
    ports:
      - "8081:8080"  # Backend direkt erreichbar auf localhost:8081 (8080 ist von Traefik Dashboard belegt)
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=database
      - DB_PORT=1521
      - DB_SERVICE=FREEPDB1
      - DB_USER=appuser
      - DB_PASSWORD=Oracle123
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Vue.js Frontend
  frontend:
    image: ghcr.io/luetzen/docker-and-kubernetes/frontend:latest
    container_name: frontend
    ports:
      - "8090:80"  # Frontend direkt erreichbar auf localhost:8090
    environment:
      - BACKEND_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  oracle-data:
    driver: local

networks:
  app-network:
    driver: bridge

