-- Initialisierungs-Skript für Oracle Database
-- Erstellt Tabellen und fügt Beispieldaten ein

-- Sequence für Product IDs
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Produkte Tabelle
CREATE TABLE PRODUCTS (
    ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PRICE NUMBER(10,2) NOT NULL,
    STOCK NUMBER(10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID)
);

-- Index für schnellere Suche
CREATE INDEX IDX_PRODUCTS_NAME ON PRODUCTS(NAME);

-- Beispieldaten einfügen
INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Laptop Dell XPS 15', 'High-Performance Laptop mit Intel i7 und 16GB RAM', 1299.99, 15, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Monitor Samsung 27"', '4K UHD Monitor mit 144Hz', 449.99, 25, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Tastatur Logitech MX Keys', 'Mechanische Tastatur mit Hintergrundbeleuchtung', 99.99, 50, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Maus Logitech MX Master 3', 'Ergonomische Wireless Maus', 89.99, 40, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Headset Sony WH-1000XM5', 'Noise-Cancelling Bluetooth Kopfhörer', 349.99, 20, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Webcam Logitech C920', 'Full HD 1080p Webcam', 79.99, 30, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'SSD Samsung 970 EVO 1TB', 'NVMe M.2 SSD mit 1TB Kapazität', 129.99, 35, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Docking Station USB-C', 'Universal Docking Station mit 4K Support', 199.99, 12, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Drucker HP LaserJet Pro', 'Schwarz-Weiß Laserdrucker', 249.99, 8, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO PRODUCTS (ID, NAME, DESCRIPTION, PRICE, STOCK, CREATED_AT, UPDATED_AT)
VALUES (PRODUCT_SEQ.NEXTVAL, 'Router ASUS RT-AX88U', 'WiFi 6 Gaming Router', 299.99, 10, SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;

-- Statistiken ausgeben
SELECT COUNT(*) AS "Anzahl Produkte" FROM PRODUCTS;
SELECT 'Datenbank initialisiert!' AS STATUS FROM DUAL;

