# Service für Docker-Datenbank auf dem Host
# Verwendet ExternalName um auf host.docker.internal zu zeigen
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: fullstack-app
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - name: oracle
    port: 1521
    protocol: TCP

