# Konfiguration für Docker Container
spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:database}:${DB_PORT:1521}/${DB_SERVICE:FREEPDB1}
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:Oracle123}

  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.example.backend: DEBUG

